# Generated by Django 2.2.14 on 2021-07-08 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='amount',
            field=models.IntegerField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
